name: nav_stack
description: A simple but powerful path-based navigation router with full web-browser and deeplink support.
version: 0.0.1
homepage: https://github.com/gskinnerTeam/flutter_nav_stack

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  path_stack: ^0.0.2+6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
